#生产环境配置
rmt:
  from_db:
    host: 10.174.113.166
    port: 27017
  to_db:
    host: 10.25.36.123
    port: 27017
  database: 9tong
  collections: user_contacts,user_gps,weibo_contacts,linkedin_contacts,contacts_update_state
  oneByOne: false
  batchCount: 1000

logging:
  path: logs
  level: info